name: pulse_bay_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
          weight: 100
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800

    - family: Barlow
      fonts:
        - asset: fonts/Barlow-Black.ttf
          weight: 100
        - asset: fonts/Barlow-Light.ttf
          weight: 300
        - asset: fonts/Barlow-Regular.ttf
          weight: 400
        - asset: fonts/Barlow-Medium.ttf
          weight: 500
        - asset: fonts/Barlow-SemiBold.ttf
          weight: 600
        - asset: fonts/Barlow-Bold.ttf
          weight: 700
        - asset: fonts/Barlow-ExtraBold.ttf
          weight: 800
    
